#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 SYSTRAN Software, Inc. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class DictionariesListMatchFilter(object):
    """
    NOTE: This class is auto generated by the systran code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        Systran model

        :param dict systran_types: The key is attribute name and the value is attribute type.
        :param dict attribute_map: The key is attribute name and the value is json key in definition.
        """
        self.systran_types = {
            'in_source_lang': 'list[str]',
            'nin_source_lang': 'list[str]',
            'in_target_langs': 'list[str]',
            'regex_comments': 'str',
            'in_nb_entries': 'list[int]',
            'nin_nb_entries': 'list[int]',
            'min_nb_entries': 'int',
            'max_nb_entries': 'int',
            'in_name': 'list[str]',
            'nin_name': 'list[str]',
            'regex_name': 'str'
        }

        self.attribute_map = {
            'in_source_lang': 'inSourceLang',
            'nin_source_lang': 'ninSourceLang',
            'in_target_langs': 'inTargetLangs',
            'regex_comments': 'regexComments',
            'in_nb_entries': 'inNbEntries',
            'nin_nb_entries': 'ninNbEntries',
            'min_nb_entries': 'minNbEntries',
            'max_nb_entries': 'maxNbEntries',
            'in_name': 'inName',
            'nin_name': 'ninName',
            'regex_name': 'regexName'
        }
        
        # Match all dictionaries with sourceLang present in a subset of values
        self.in_source_lang = None  # list[str]
        
        # Match all dictionaries with sourceLang not present in a subset of values
        self.nin_source_lang = None  # list[str]
        
        # Match all dictionaries with targetLang from a subset of values present in targetLangs property
        self.in_target_langs = None  # list[str]
        
        # Match all entries with comments containing the specified value
        self.regex_comments = None  # str
        
        # Match all dictionaries with nbEntries present in a subset of values
        self.in_nb_entries = None  # list[int]
        
        # Match all dictionaries with nbEntries not present in a subset of values
        self.nin_nb_entries = None  # list[int]
        
        # Match all entries with nbEntries equal and over specified value
        self.min_nb_entries = None  # int
        
        # Match all entries with nbEntries under and equal specified value
        self.max_nb_entries = None  # int
        
        # Match all entries with name present in a subset of values
        self.in_name = None  # list[str]
        
        # Match all entries with name not present in a subset of values
        self.nin_name = None  # list[str]
        
        # Match all entries with name containing the specified value
        self.regex_name = None  # str
        

    def __repr__(self):
        properties = []
        for p in self.__dict__:
            if p != 'systran_types' and p != 'attribute_map':
                properties.append('{prop}={val!r}'.format(prop=p, val=self.__dict__[p]))

        return '<{name} {props}>'.format(name=__name__, props=' '.join(properties))


