#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 SYSTRAN Software, Inc. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


class EntryOutput(object):
    """
    NOTE: This class is auto generated by the systran code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        Systran model

        :param dict systran_types: The key is attribute name and the value is attribute type.
        :param dict attribute_map: The key is attribute name and the value is json key in definition.
        """
        self.systran_types = {
            'source': 'str',
            'target': 'str',
            'part_of_speech': 'str',
            'priority': 'int',
            'comments': 'str',
            'source_confidence': 'int',
            'target_confidence': 'int',
            'source_lang': 'str',
            'target_lang': 'str',
            'source_id': 'str',
            'target_id': 'str'
        }

        self.attribute_map = {
            'source': 'source',
            'target': 'target',
            'part_of_speech': 'partOfSpeech',
            'priority': 'priority',
            'comments': 'comments',
            'source_confidence': 'sourceConfidence',
            'target_confidence': 'targetConfidence',
            'source_lang': 'sourceLang',
            'target_lang': 'targetLang',
            'source_id': 'sourceId',
            'target_id': 'targetId'
        }
        
        
        self.source = None  # str
        
        
        self.target = None  # str
        
        
        self.part_of_speech = None  # str
        
        
        self.priority = None  # int
        
        
        self.comments = None  # str
        
        
        self.source_confidence = None  # int
        
        
        self.target_confidence = None  # int
        
        
        self.source_lang = None  # str
        
        
        self.target_lang = None  # str
        
        
        self.source_id = None  # str
        
        
        self.target_id = None  # str
        

    def __repr__(self):
        properties = []
        for p in self.__dict__:
            if p != 'systran_types' and p != 'attribute_map':
                properties.append('{prop}={val!r}'.format(prop=p, val=self.__dict__[p]))

        return '<{name} {props}>'.format(name=__name__, props=' '.join(properties))


